version: '3'

services:
  web: &defaults
    build: ./
    ports:
      - 8000:80
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    tty: true
    privileged: true
    working_dir: "/var/www/html"
    restart: always
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - .db:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
       - 8005:80
    volumes:
       - /sessions
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1081:1080"
      - "1026:1025"
