<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateRecruitInfoOnesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('recruit_info_ones', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('status');
            $table->integer('company_id');
            $table->string('model_case_name');
            $table->string('recruit_amount_this_year');
            $table->string('recruit_amount_last_year');
            $table->string('deadline_web_pre_entry');
            $table->string('deadline_web_pre_entry_term');
            $table->string('deadline_entry_sheat');
            $table->string('deadline_entry_sheat_term');
            $table->string('term_seminar_date');
            $table->string('term_seminar_date_term');
            $table->string('term_interview_date');
            $table->string('term_interview_date_term');
            $table->string('term_offering_date');
            $table->string('term_offering_date_term');
            $table->boolean('submit_sheat_is_needed')->nullable();
            $table->boolean('submit_sheat_open_es');
            $table->boolean('submit_sheat_entry_sheat');
            $table->boolean('submit_sheat_resume');
            $table->boolean('submit_sheat_score_sheat');
            $table->boolean('submit_sheat_others');
            $table->string('salary_model');
            $table->string('month_salary_example');
            $table->boolean('others_three_year_ninety');
            $table->boolean('others_average_fifteen');
            $table->boolean('others_paid_vacation');
            $table->boolean('others_all_holiday');
            $table->boolean('others_no_more_work');
            $table->boolean('others_less_than_twenty_more_work');
            $table->boolean('others_more_than_two_week_vacation');
            $table->boolean('others_raise_holiday_ninety');
            $table->boolean('others_raise_nursing_holiday_fifty');
            $table->boolean('others_woman_boss_twenty');
            $table->boolean('others_woman_board_member');
            $table->boolean('others_remote_work');
            $table->boolean('others_no_moving');
            $table->boolean('others_oversea_work');
            $table->boolean('others_using_english');
            $table->boolean('others_more_than_thirty_fresh_worker');
            $table->boolean('others_thirty_years_boss');
            $table->boolean('others_new_ring');
            $table->boolean('others_side_work');
            $table->boolean('others_rent_money');
            $table->boolean('others_get_license');
            $table->boolean('others_family_money');
            $table->boolean('others_flexible_change_division');
            $table->boolean('others_variable_division');
            $table->boolean('others_help_startup');
            $table->boolean('is_model_2');
            $table->string('model_case_name_2');
            $table->string('recruit_amount_this_year_2');
            $table->string('recruit_amount_last_year_2');

            $table->string('deadline_web_pre_entry_2');
            $table->string('deadline_web_pre_entry_term_2');
            $table->string('deadline_entry_sheat_2');
            $table->string('deadline_entry_sheat_term_2');
            $table->string('term_seminar_date_2');
            $table->string('term_seminar_date_term_2');
            $table->string('term_interview_date_2');
            $table->string('term_interview_date_term_2');
            $table->string('term_offering_date_2');
            $table->string('term_offering_date_term_2');

            $table->boolean('submit_sheat_is_needed_2')->nullable();
            $table->boolean('submit_sheat_open_es_2');
            $table->boolean('submit_sheat_entry_sheat_2');
            $table->boolean('submit_sheat_resume_2');
            $table->boolean('submit_sheat_score_sheat_2');
            $table->boolean('submit_sheat_others_2');
            $table->string('salary_model_2');
            $table->string('month_salary_example_2');
            $table->boolean('others_three_year_ninety_2');
            $table->boolean('others_average_fifteen_2');
            $table->boolean('others_paid_vacation_2');
            $table->boolean('others_all_holiday_2');
            $table->boolean('others_no_more_work_2');
            $table->boolean('others_less_than_twenty_more_work_2');
            $table->boolean('others_more_than_two_week_vacation_2');
            $table->boolean('others_raise_holiday_ninety_2');
            $table->boolean('others_raise_nursing_holiday_fifty_2');
            $table->boolean('others_woman_boss_twenty_2');
            $table->boolean('others_woman_board_member_2');
            $table->boolean('others_remote_work_2');
            $table->boolean('others_no_moving_2');
            $table->boolean('others_oversea_work_2');
            $table->boolean('others_using_english_2');
            $table->boolean('others_more_than_thirty_fresh_worker_2');
            $table->boolean('others_thirty_years_boss_2');
            $table->boolean('others_new_ring_2');
            $table->boolean('others_side_work_2');
            $table->boolean('others_rent_money_2');
            $table->boolean('others_get_license_2');
            $table->boolean('others_family_money_2');
            $table->boolean('others_flexible_change_division_2');
            $table->boolean('others_variable_division_2');
            $table->boolean('others_help_startup_2');
            $table->string('audition_border_image');
            $table->text('audition_border');
            $table->string('requirement_title_1');
            $table->text('requirement_description_1');
            $table->string('requirement_title_2');
            $table->text('requirement_description_2');
            $table->string('requirement_title_3');
            $table->text('requirement_description_3');
            $table->string('requirement_title_4');
            $table->text('requirement_description_4');
            $table->string('requirement_title_5');
            $table->text('requirement_description_5');
            $table->string('requirement_title_6');
            $table->text('requirement_description_6');
            $table->string('requirement_title_7');
            $table->text('requirement_description_7');
            $table->string('requirement_title_8');
            $table->text('requirement_description_8');
            $table->string('requirement_title_9');
            $table->text('requirement_description_9');
            $table->string('requirement_title_10');
            $table->text('requirement_description_10');
            $table->string('welfare_title_1');
            $table->text('welfare_description_1');
            $table->string('welfare_title_2');
            $table->text('welfare_description_2');
            $table->string('welfare_title_3');
            $table->text('welfare_description_3');
            $table->string('welfare_title_4');
            $table->text('welfare_description_4');
            $table->string('welfare_title_5');
            $table->text('welfare_description_5');
            $table->string('welfare_title_6');
            $table->text('welfare_description_6');
            $table->string('welfare_title_7');
            $table->text('welfare_description_7');
            $table->string('welfare_title_8');
            $table->text('welfare_description_8');
            $table->string('welfare_title_9');
            $table->text('welfare_description_9');
            $table->string('welfare_title_10');
            $table->text('welfare_description_10');
            $table->string('welfare_title_11');
            $table->text('welfare_description_11');
            $table->string('welfare_title_12');
            $table->text('welfare_description_12');
            $table->string('welfare_title_13');
            $table->text('welfare_description_13');
            $table->string('welfare_title_14');
            $table->text('welfare_description_14');
            $table->string('welfare_title_15');
            $table->text('welfare_description_15');
            $table->dateTime('robo_export_at')->nullable();
            $table->integer('answer_count');
            $table->integer('answer_allcount');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('recruit_info_ones');
    }
}
